spring.application.name=paytm

spring.datasource.url=jdbc:postgresql://localhost:5432/seat_reservation
spring.datasource.username=app
spring.datasource.password=app

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata